### ISSUE TITLE
Fill README.md 

### ISSUE THREAD

**Issue by MaksymDel** [alexanderguk/Match3#1]
I think it's a good idea to add main features and other info about project to README.md.

**Comment by alexanderguk** [comment]
As well as create the whole game.

**Comment by MaksymDel** [comment]
The point is to add to the README list of main features, and label some features as "done \ in progress \ expected".

If you do this, there will be a good view of what the project actually is and what the project actually will be in future.

**Comment by alexanderguk** [comment]
Nobody knows how it will be in the future.
